"$schema" = "./node_modules/wrangler/config-schema.json"
name = "poc-cloudflare-turnstile"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2026-09-22"
compatibility_flags = ["nodejs_als"]

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "28716dbd50314b05ae2727abe4c6ae20"

[vars]
RATE_LIMIT_WINDOW = "600"
RATE_LIMIT_PER_PHONE = "3"
RATE_LIMIT_PER_IP = "10"
PUBLIC_TURNSTILE_SITEKEY = "0x4AAAAAAFAcQfGn7tQjl080"

[env.preview]
[[env.preview.kv_namespaces]]
binding = "RATE_LIMIT"
id = "28716dbd50314b05ae2727abe4c6ae20"

[env.preview.vars]
RATE_LIMIT_WINDOW = "600"
RATE_LIMIT_PER_PHONE = "3"
RATE_LIMIT_PER_IP = "10"
PUBLIC_TURNSTILE_SITEKEY = "1x00000000000000000000AA"
